---
title: "Figure 2"
author: "Wenqing Hong"
date: "2023-08-29"
output:
  html_document: default
  pdf_document: default
---
#Please Use ggplot2_3.4.2
```{r}
rm(list = ls())
```

```{r}
library(tidyverse)
library(reshape2)
library(cowplot)
library(aplot)
otu <- read.csv("REotu.csv")
sample_info <- read.csv("group.csv",row.names = 1)
tax <- read.csv("taxon.csv")
```

```{r}
df1 <- 
  otu %>%
  column_to_rownames(var = "ID") %>%
  mutate(sum = rowSums(.)) %>%
  select(sum) %>% 
  arrange(desc(sum)) %>% 
  top_n(30)

df2 <- 
  tax %>% 
  filter(ID %in% rownames(df1))
```
```{r}
p3 <- 
  df2 %>% 
  ggplot() + 
  geom_text(aes(x = 'OTU', y = ID, label = ID), size = 3) +
  scale_x_discrete(position = "top") +
  labs(x = "", y = "") + 
  theme_nothing() + 
  theme(panel.grid = element_blank(),
        axis.text.x.top = element_text(size = 10),
        axis.ticks = element_blank())

p_OTU <- 
  p3 +
  geom_hline(yintercept = c(30.5, 31.5, 0.5), size = 1)
p_OTU
```

```{r}
pic <- function(level){
  df2 %>% 
    select(c(level, 'ID')) %>% 
    set_names(c('label', 'ID')) %>% 
    mutate(Info = str_split(label, pattern = "_", simplify = T)[,3]) %>%
    ggplot() + 
    geom_text(aes(x = level, y = ID, label = Info), size = 3) +
    scale_x_discrete(position = "top") +
    labs(x = "", y = "") + 
    theme_nothing() + 
    theme(panel.grid = element_blank(),
          axis.text.x.top = element_text(size = 10),
          axis.ticks = element_blank())
}

p_Phylum <- 
  pic('Phylum') +
  geom_hline(yintercept = c(30.5, 31.5, 0.5), size = 1) 

p_Phylum

p_Genus <- 
  pic('Genus') +
  geom_hline(yintercept = c(30.5, 31.5, 0.5), size = 1)

p_Genus

p_Phylum %>% 
  insert_right(p_Genus)
```


```{r}
p_type <-  
  otu %>% 
  filter(ID %in% rownames(df1)) %>% 
  column_to_rownames('ID') %>% 
  t() %>% 
  as.data.frame() %>% 
  rownames_to_column('SampleID') %>% 
  left_join(sample_info) %>% 
  group_by(Type) %>% 
  summarise_if(is.numeric, sum, na.rm = TRUE) %>% 
  reshape2::melt() %>% 
  ggplot() + 
  geom_point(aes(x = Type, y = variable,fill = Type, size = value), shape = 21) + 
  scale_size_area(max_size = 10) +
  scale_x_discrete(position = "top") +
  scale_fill_manual(values = c("#B2182B","#E69F00","#999999","#009E73","#F0E442","#0072B2","#D55E00","#CC79A7","#CC6666","#56B4E9"))+
  labs(x = "", y = "") + 
  guides(fill = "none",
         size = guide_legend(ncol = 1)) + 
  theme_bw() + 
  theme(panel.grid = element_blank(),
        axis.text.x.top = element_text(size = 10, angle = 45, hjust = 0, color = "black"),
        axis.text.y.right = element_text(size = 10, color = "black"),
        axis.ticks = element_blank(),
        axis.text.y = element_blank())
p_type

P <- p_Phylum %>% 
  insert_right(p_Genus) %>% 
  insert_right(p_OTU, width = 0.3) %>% 
  insert_right(p_type, width = 2)
P
ggsave(P,filename = "Figure 2.pdf", height = 10, width = 10)
```