---
title: "Figure3 E"
author: "Wenqing Hong"
date: "2023-08-05"
output:
  html_document: default
  pdf_document: default
---
```{r}
rm(list = ls())
```


```{r}
library(ggplot2)
library(vegan)
library(ape)
library(RColorBrewer)
library(ggstar)
library(ggrepel)
```

```{r}
data <- read.csv(file = "vulnerability.csv",header = T)
```

```{r}
p <- ggplot(data, aes(sample,vulnerability, group = "1")) +
    geom_path(size = 2, color = "#56B4E9") +
    geom_point(size = 6, color = "#56B4E9", shape = 17) +
    theme(panel.background = element_blank(),
          axis.line = element_line())
p 
ggsave("Vulnerability.pdf", width = 12, height = 5)
```

```{r}
data1 <- read.csv(file = "Robustedness.csv",header = T)
```

```{r}
p1 <- ggplot(data1, aes(x= time, y=value ,color=type,fill=type,shape=type))+
  scale_shape_manual(values=c(22,24))+
  scale_fill_manual(values=c("#009E73"))+
  scale_color_manual(values=c("#009E73")) +
  scale_y_continuous(expand = c(0, 0))+
  scale_x_continuous(breaks=seq(0,8,1))+
  geom_line(size=1.5)+
  geom_ribbon(aes(ymin = value-se,
                  ymax = value+se),fill = "#009E73",alpha=0.2) +
  geom_point(color="#009E73",size=10,shape=17)+
  labs(title="",x="Sampling sites", y = "Robustedness_50.unweighted")+
  theme_bw()+
  theme(panel.grid=element_blank()) +
  theme(panel.border = element_blank()) +
  theme(panel.background=element_rect(fill='transparent', color='black'),plot.margin = unit(c(3,5,1,1),"mm"))+
  theme(axis.text.x=element_text(colour="black",size=30,face = "bold",vjust = 0.5,hjust = 0)) +
  theme(axis.text.y=element_text(colour = "black",size = 30)) +
  theme(axis.line = element_line(colour = "black"))+
  theme(legend.text = element_text(colour = "black",size = 30)) +
  theme(legend.title = element_text(size = 30,colour = "black")) +
  theme(axis.title.y = element_text(size = 30,face = "bold",margin = unit(c(0,1,0,1),"lines")))+
  theme(axis.title.x = element_text(size = 30,face = "bold",margin = unit(c(0,1,0,1),"lines")))+
  scale_x_continuous(breaks =seq(1,8,1), labels = data1$group)
p1 
ggsave("Robustedness.pdf", width = 20, height = 8)
```
